// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(DNDContext))]
    partial class DNDContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("WebAPI.Models.SurveyResponse", b =>
                {
                    b.Property<int>("SurveyResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanySize")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateSent")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectDuration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Question1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Question2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Question3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Question4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Question5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Question6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Question7")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Question8")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Question9")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SurveyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SurveyResponseId");

                    b.ToTable("SurveyResponses");
                });
#pragma warning restore 612, 618
        }
    }
}
