@startuml
class GreenHouseT {
    + GreenHouseId : int <<get>> <<set>>
    + Unit : string? <<get>> <<set>>
    + scope12Market : double <<get>> <<set>>
    + scope12location : double <<get>> <<set>>
    + scope3soldproducts : double <<get>> <<set>>
}
GreenHouseT --> "Year" DateTime
@enduml
