@startuml
!include .\\FileStorage\DataContainer.puml
!include .\\FileStorage\FileContext.puml
!include .\\FileStorage\FileDataService.puml
!include .\\FileStorage\FileUserService.puml
!include .\\WebAPI\Program.puml
!include .\\WebApp\Program.puml
!include .\\Application\Interfaces\IDataService.puml
!include .\\Application\Interfaces\IUserService.puml
!include .\\Domain\Auth\AuthorizationPolicies.puml
!include .\\Domain\DTOs\UserLoginDto.puml
!include .\\Domain\Models\Data.puml
!include .\\Domain\Models\User.puml
!include .\\WebAPI\Controllers\AuthController.puml
!include .\\WebAPI\Controllers\DatasController.puml
!include .\\WebAPI\Controllers\DNDContext.puml
!include .\\WebAPI\Controllers\TestController.puml
!include .\\WebAPI\Controllers\UsersController.puml
!include .\\WebAPI\Migrations\20241216130301_InitialCreate.puml
!include .\\WebAPI\Migrations\20241216130301_InitialCreate.Designer.puml
!include .\\WebAPI\Migrations\DNDContextModelSnapshot.puml
!include .\\WebAPI\Models\Edata.puml
!include .\\WebAPI\Models\EdataK.puml
!include .\\WebAPI\Models\Greenhouse.puml
!include .\\WebAPI\Models\GreenhouseK.puml
!include .\\WebAPI\Models\GreenhouseT.puml
!include .\\WebAPI\Models\Waste.puml
!include .\\WebAPI\Models\WasteK.puml
!include .\\WebAPI\Models\WasteT.puml
!include .\\WebAPI\Models\Water.puml
!include .\\WebAPI\Models\WaterK.puml
!include .\\WebAPI\Services\AuthService.puml
!include .\\WebAPI\Services\EdataService.puml
!include .\\WebAPI\Services\IAuthService.puml
!include .\\WebApp\Auth\CustomAuthProvider.puml
!include .\\WebApp\Services\Http\IAuthService.puml
!include .\\WebApp\Services\Http\JwtAuthService.puml
!include .\\Application\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\Application\obj\Debug\net8.0\Application.AssemblyInfo.puml
!include .\\Application\obj\Debug\net8.0\Application.GlobalUsings.g.puml
!include .\\Domain\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\Domain\obj\Debug\net8.0\DNDProject.Domain.AssemblyInfo.puml
!include .\\Domain\obj\Debug\net8.0\DNDProject.Domain.GlobalUsings.g.puml
!include .\\Domain\obj\Debug\net8.0\Domain.AssemblyInfo.puml
!include .\\Domain\obj\Debug\net8.0\Domain.GlobalUsings.g.puml
!include .\\FileStorage\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\FileStorage\obj\Debug\net8.0\DNDProject.FileStorage.AssemblyInfo.puml
!include .\\FileStorage\obj\Debug\net8.0\DNDProject.FileStorage.GlobalUsings.g.puml
!include .\\FileStorage\obj\Debug\net8.0\FileStorage.AssemblyInfo.puml
!include .\\FileStorage\obj\Debug\net8.0\FileStorage.GlobalUsings.g.puml
!include .\\WebAPI\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\WebAPI\obj\Debug\net8.0\DNDProject.WebAPI.AssemblyInfo.puml
!include .\\WebAPI\obj\Debug\net8.0\DNDProject.WebAPI.GlobalUsings.g.puml
!include .\\WebAPI\obj\Debug\net8.0\DNDProject.WebAPI.MvcApplicationPartsAssemblyInfo.puml
!include .\\WebAPI\obj\Debug\net8.0\WebAPI.AssemblyInfo.puml
!include .\\WebAPI\obj\Debug\net8.0\WebAPI.GlobalUsings.g.puml
!include .\\WebAPI\obj\Debug\net8.0\WebAPI.MvcApplicationPartsAssemblyInfo.puml
!include .\\WebApp\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\WebApp\obj\Debug\net8.0\WebApp.AssemblyInfo.puml
!include .\\WebApp\obj\Debug\net8.0\WebApp.GlobalUsings.g.puml
!include .\\WebApp\obj\Debug\net8.0\WebApp.MvcApplicationPartsAssemblyInfo.puml
@enduml
